name: Fixed React Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build:github

      - name: Fix potential routing issues
        run: |
          # Copy 404.html for better SPA support
          cp ./dist/public/404.html ./dist/public/200.html
          # List final structure
          echo "=== FINAL DEPLOYMENT FILES ==="
          find ./dist/public -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -20

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
